# Generated by Django 3.1 on 2020-08-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200814_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_membership',
        ),
    ]
