# Generated by Django 3.1 on 2020-08-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthquestions',
            old_name='Where_you_hear',
            new_name='where_you_hear',
        ),
        migrations.RemoveField(
            model_name='healthquestions',
            name='user',
        ),
    ]
