# Generated by Django 3.1 on 2020-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembersPage',
            new_name='Article',
        ),
    ]
