# Generated by Django 3.1 on 2020-08-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200822_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthQuestions',
        ),
    ]
