# Generated by Django 3.1 on 2020-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_often', models.CharField(max_length=100)),
                ('what_times', models.CharField(max_length=100)),
                ('favourite_way', models.CharField(max_length=100)),
                ('supplement', models.CharField(max_length=100)),
                ('where_you_hear', models.CharField(max_length=100)),
            ],
        ),
    ]
