# Generated by Django 3.1 on 2020-08-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
        ('checkout', '0003_auto_20200817_1634'),
    ]

    operations = [
    ]
