# Generated by Django 3.1 on 2020-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200808_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
